name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login - Docker Hub
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Docker Hub
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/apicanaldoleo:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/apicanaldoleo:latest ${{ secrets.DOCKER_USERNAME }}/apicanaldoleo:$(date +%s)
        docker push ${{ secrets.DOCKER_USERNAME }}/apicanaldoleo

    - name: Logando no Azure para Deployment
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp Container - Deployment da Aplicacao
      uses: Azure/webapps-container-deploy@v1
      with:
        app-name: groffeapidocker2
        images: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicanaldoleo:latest
